# Generated by Django 2.2.7 on 2019-11-16 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200)),
                ('country_population', models.IntegerField()),
            ],
            options={
                'ordering': ['country_name'],
            },
        ),
        migrations.CreateModel(
            name='CropClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['class_name'],
            },
        ),
        migrations.CreateModel(
            name='CropGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['group_name'],
            },
        ),
        migrations.CreateModel(
            name='CropSubClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subclass_name', models.CharField(max_length=200)),
                ('cropclass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.CropClass')),
            ],
            options={
                'ordering': ['subclass_name'],
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=500)),
                ('telephone1', models.CharField(max_length=13)),
                ('telephone2', models.CharField(max_length=13)),
                ('enailAddress', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('description', models.TextField(help_text='Enter a brief description of the farm', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=200)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Country')),
            ],
            options={
                'ordering': ['state_name'],
            },
        ),
        migrations.CreateModel(
            name='ProduceStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Enter a brief description of the produce', max_length=1000)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=16)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cropclass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.CropClass')),
                ('cropsubclass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.CropSubClass')),
                ('farm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='LocalGovt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localgovt_name', models.CharField(max_length=200)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.State')),
            ],
            options={
                'ordering': ['localgovt_name'],
            },
        ),
        migrations.AddField(
            model_name='farm',
            name='localgovt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.LocalGovt'),
        ),
        migrations.AddField(
            model_name='cropclass',
            name='cropgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.CropGroup'),
        ),
    ]
