# Generated by Django 2.2.7 on 2019-11-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191116_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='capital',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
