# Generated by Django 2.2.7 on 2019-11-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20191117_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='slogan',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
